"""add task table update

Revision ID: 12ae389986b3
Revises: 6535654405d4
Create Date: 2021-01-15 16:09:37.949119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12ae389986b3"
down_revision = "6535654405d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("updated_on_gateway", sa.Boolean(), server_default="0", nullable=False),
    )
    op.add_column("task", sa.Column("updated_on_gateway_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "updated_on_gateway_at")
    op.drop_column("task", "updated_on_gateway")
    # ### end Alembic commands ###
