"""add mixins

Revision ID: cff876cf7d40
Revises: 12ae389986b3
Create Date: 2021-01-18 15:51:03.279756
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cff876cf7d40'
down_revision = '12ae389986b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'task', sa.Column('created_by_id', sa.Integer(), nullable=True)
    )
    op.add_column(
        'task', sa.Column('date_created', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'task', sa.Column('date_updated', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'task', sa.Column('updated_by_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_by_id')
    op.drop_column('task', 'date_updated')
    op.drop_column('task', 'date_created')
    op.drop_column('task', 'created_by_id')
    # ### end Alembic commands ###
