[development]
APP_VERSION="1"
DB_DSN = "postgresql+asyncpg://postgres_user:pass123@localhost:5432/todo"
MAIN_APP ="example"
API_V1_STR = "/todo"
APP_NAME = "todo"

[testing]
DB_DSN = "postgresql+asyncpg://postgres_user:pass123@localhost:5432/todo_test"
MAIN_APP ="example"
API_V1_STR = "/todo"
APP_NAME = "todo"

